### ISSUE TITLE
Add motion/human sensor

### ISSUE THREAD

**Issue by Brix1330** [user2684/imou_life#15]
Is it possible to add motion/human detection sensor of the camera?

My device is Imou Cruiser 4MP (IPC-S42F-D).

**Comment by user2684** [comment]
Hi, this should be already possible provided the camera exposes the right capability. If it is not the case, please download diagnostics from the device in HA and share it here :-) Thanks!

**Comment by Brix1330** [comment]
There's switch but no sensor entity.

![screens](https://user-images.githubusercontent.com/34420899/201522527-547e5007-be36-4a53-aefd-66a6d5f32e14.png)

Diagnostics:
[config_entry-imou_life-609d674ba2e9b14cfb6dbdb1f61eb381.txt](https://github.com/user2684/imou_life/files/9997201/config_entry-imou_life-609d674ba2e9b14cfb6dbdb1f61eb381.txt)

**Comment by user2684** [comment]
Oh I see your point. Unfortunately, since the Imou API does not provide a stream of events, the only way to get realtime notifications (including motion events) is by configuring push notifications as per https://github.com/user2684/imou_life#push-notifications. This would require setting up an automation  which takes care of handling the event itself. I've a roadmap item to provide some sort of template / blueprint to handle this process in a more simple way

**Comment by user2684** [comment]
This should be fixed with version 1.0.6 (https://github.com/user2684/imou_life#motion-detection)
