### ISSUE TITLE
how to watch video with this integration

### ISSUE THREAD

**Issue by Whastie** [user2684/imou_life#18]
Hello

I have done the integration and I have access to all the sensors of the integration.

But how can I see the video of the camera with this integration?
I don't see the video sensor in the integration.
I would like to be able to move the camera motor and view the video in both quality profiles.
With this integration I can access via rstp ? until now it was not possible with this type of camera.
Is it possible ?

Thanks

![image](https://user-images.githubusercontent.com/89639919/202028342-2f42b34d-d635-414e-92fc-dc513d8959a9.png)

**Comment by user2684** [comment]
Hi, correct, streaming the video out of the camera is not a capability available at this time. Reason is I wanted to avoid features already implemented in other integrations and since the Onvif integration works just fine and is faster (direct access to the camera without the need to go through the cloud service), I think is a better option. RTSP would not be possible through the Imou API, theoretically we could be able to stream like the Imou Life app does, even if the implementation would be pretty complex. Do you see any specific use case which would prevent you from using onvif for video streaming?
Thanks

**Comment by user2684** [comment]
I expect onvif to be in any case faster than using the Imou Api since interacting directly with the camera while through Imou is going through the internet and hence there will be a consistent delay. Regarding RTSP, looking at the api documentation (https://open.imoulife.com/book/en/http/device/live/bindDeviceLive.html?h=rtsp) I still don't get if it is exposing rtsp in the cloud or something different. I need for sure to do some more investigation to understand how it works since that piece of API is a bit complex. Adding it to the roadmap. Thanks

**Comment by PonyOny** [comment]
@Whastie
You can integrate the cameras in frigate, the only main problem is you have to change the camera encoding from H.265 to H.264 to do this you need to do it with Imou [Config Tool](https://www.imoulife.com/uk/support/download/tools)
if you need the connection url for your camera you can get ir from [here](https://www.ispyconnect.com/camera/imou)

**Comment by user2684** [comment]
Switching from H.265 to H.264 is required also when using the camera in HA through onvif. Not a HA issue per se but no browser looks like are capable of handling a H.265 stream :-)

**Comment by xCapeITA** [comment]
First of all a big THANKS for this integration.
Yes, you are right, ONVIF is stable and fast altough is limited to H264 and you must have a fixed IP on camera.
This said I will not make use of video integration if implemented since is nt RSTP and (i think) implies HA to be exposed to internet.

BUT 

I'd love to have screenshot for alarms in ALL devices. I do not know why the hell some cameras make use of CGI implementations and others don't!! Maybe screencapping the stream is a way?

**Comment by user2684** [comment]
I think there are two options here we can explore: screenshots on motion and screenshots on demand when e.g. pressing a button. Which one do you think we should focus on? Thanks

**Comment by casti123** [comment]
IHMO screenshot on demand is a more flexible solution for HA.

I can have a snapshot on motion by simply requesting it on demand with a rule (If motion>snapshot). Plus I can have snapshots with fantasy as only limit (currently I have a rule that send me a snapshot every 10minutes if the garage door remains open)

**Comment by xCapeITA** [comment]
IHMO screenshot on demand is a more flexible solution for HA.

I can have a snapshot on motion by simply requesting it on demand with a rule (If motion>snapshot). Plus I can have snapshots with fantasy as only limit (currently I have a rule that send me a snapshot every 10minutes if the garage door remains open)

**Comment by user2684** [comment]
Agree. Let me prioritize this. Two things to solve:
- API to call to generate the screenshot (this should be easy - https://open.imoulife.com/book/en/http/device/operate/setDeviceSnap.html)
- Ability to convert from dav to a different format (so far I've seen only dav encrypted formats out of the different APIs)

Will have a look at both

**Comment by user2684** [comment]
Should be solved, have a look at this https://community.home-assistant.io/t/imou-life-cloud-integration/462439/125 :-)
