### ISSUE TITLE
Support additional Imou device: vacuum cleaner

### ISSUE THREAD

**Issue by user2684** [user2684/imou_life#23]
Looks like they are leveraging a completely different set of APIs

**Comment by thewan056** [comment]
I am using Imou light bulbs. I believe Imou are using Tuya/SmartLife platform for their other IOT devices. The interface looks really similar.  

I would like to see HA support them if possible since the Imou app is really lacking in terms of automation features for their bulbs. And the automation that is available is very clunky, confusing and not user friendly.
Admittedly I made a mistake buying these and I didn't know that it would be that bad as there are a lack of reviews on the internet. Maybe one day I'll switch them out for something else. Meanwhile I hope I could one day make them smarter with HA.

**Comment by user2684** [comment]
Hi, wonder if by using the Tuya integration in HA you see this device and can control it, just as a starting point.
If not we may try to have a look at this different set of APIs even if means starting from scratch more or less and may take some time :-)

**Comment by Dunkelschunkel** [comment]
@user2684 I have recently purchased a vacuum imou RV-L11-A and I'm would like to know if I can assist you in any way possible?

**Comment by TheFelix93** [comment]
I recently bought the imou L11. This and the pro version had I big discount and seem to be the cheapest version of this cleaner (seems to be relabeled by multiple companies).
I guess the interest will be there to have an integration :)
At least I would be really happy I there are some improvements for the imou vacuum cleaner devices.

**Comment by matthiaslexer** [comment]
I also recently bought the L11 and would love to have it integrated. 
Any plans to add it?

**Comment by user2684** [comment]
Hi, very unlikely to be honest, unless somebody has access to Imou API documentation for these devices. Unfortunately Imou is not releasing up to date API documentation to allow third party interacting with the device making reverse engineering very difficult :-/

**Comment by user2684** [comment]
Closing this for now until there will be a documented API available from Imou for the implementation
