### ISSUE TITLE
Push notifications set problem

### ISSUE THREAD

**Issue by array81** [user2684/imou_life#29]
I have 2 problem with push notifications:

FIRST PROBLEM
I have set the webhook callback on settings, like this:
"https://MYDOMAIN.duckdns.org/api/webhook/MYCALLBACKSTRING" (without port number, right?)

Then I tried to active Push Notifications about configuration of a device and I get this error:
"OP1003: Invalid parameter (incorrect or null), please modify parameter"

SECOND PROBLEM
I installed HA core on docker, so I don't have add. So I installed Nginx Proxy Manager and MariaDB both on docker and So I they seem to work. 
Could someone tell me how to set up Nginx because I don't know it (a screenshot is welcome).

**Comment by user2684** [comment]
Yes you need the port if exposed to the Internet with the port :-) 
When you configure the callback url, the imou server first tries to reach the provided url, if fails because unreachable, you get OP1003: Invalid parameter. So I'm expecting your problem to be missing port here.

Regarding nginx, you don't need Proxy Manager and MariaDB, a plain nginx worked at least for me. This scenario needs to be documented, good advice. Will work on it. Meanwhile, if you want to give a try, in my test I just added a directive like the below, pointing to HA. Also ensure there are no catch all type of servers in nginx otherwise would not work. Again, I'll document this better shortly.

```
location /{
        proxy_pass http://192.168.0.159:8123/;
    }

```

**Comment by array81** [comment]
Do I need to use any special Nginx configuration if I use SSL with Home Assistant?

I'm not succeeding with mine.

`http {
    server {
        listen       443;
        listen  [::]:443;
        server_name  localhost;

        proxy_buffering off;

        location /{
            proxy_pass https://localhost:8123/;
        }
    }
}`

**Comment by array81** [comment]
I use 8123 port for HA and SSL so I have try this but not works:

```
events {

}

http {
    server {
        listen 8123;
        location /{
            proxy_pass https://localhost:8123/;
        }
    }
}
```

**Comment by user2684** [comment]
Let me do some more tests so to share with you a working configuration ready to use for both http and https scenarios :-)

**Comment by user2684** [comment]
Added sample configuration file in Option 3 of https://github.com/user2684/imou_life#motion-detection
