### ISSUE TITLE
imou cell 2 request

### ISSUE THREAD

**Issue by checkiecheck** [user2684/imou_life#36]
So, adding this camera gives a few sensors and stuff which temporarily work. As the camera is a battery operated one, it goes to sleep.

Looking at the http api's, I think it could enable query the device to wake up and then pull sensor states. Also could not get webhooks working to have entities update.
So request is:
 - wake up device implementation
 - webhook fix (could not get any debug info on it, imou wasnt very clear when webooks are sent)
 - fetch a live stream to display as camera on awake device (which also happens on motion detection)

**Comment by user2684** [comment]
Interesting, for sure battery powered devices need to be handled differently. This is also related to an issue when a standard the device is offline with requests throwing errors. Will have a look at it, adding to the roadmap. Thanks

**Comment by user2684** [comment]
Could you please start sharing Diagnostics (https://github.com/user2684/imou_life#troubleshooting) so I can have a look at available capabilities? I don't have the same model so I need to kind of reverse engineer the behavior :-) Thanks

**Comment by checkiecheck** [comment]
> Could you please start sharing Diagnostics (https://github.com/user2684/imou_life#troubleshooting) so I can have a look at available capabilities? I don't have the same model so I need to kind of reverse engineer the behavior :-) Thanks

see above, not sure this is the format you wanted :)

**Comment by user2684** [comment]
Perfect thanks! I see the capability "Dormant" which helps us identifying those models. 
But not sure I to wake them up, is not very clear from the API documentation. The only which is closer is https://open.imoulife.com/book/en/http/door/wakeUpDevice.html even if it does not refer to cameras. 
I need to put together  some scripts asking you to run some tests for me since I do not have this model. 
Would you be confortable in running some python code for me? thanks

**Comment by checkiecheck** [comment]
sure.. let me have it. (did support other custom components before, not being developer but i get around on a PI https://community.home-assistant.io/t/apsystems-aps-ecu-r-local-inverters-data-pull/260835)

let me see which API thought was usefull from this list https://open.imoulife.com/book/http/device/manage/query/summary.html
if we cant figure it from docs, i can see if i can trace the imo life app a bit to see how that app is waking the device (it reallly states in app, waking device and then fetches a thumbnail and/or stream)

**Comment by checkiecheck** [comment]
Found only a packet with this as content, not exactly sure what it does really:
POST /device/{deviceidentifier}/local-channel 
HTTP/1.1
x-pcs-request-id: 3b390326708f8b6c89c697fae9578b47
CSeq: 1366158627
Authorization: WSSE profile="UsernameToken"
X-WSSE: UsernameToken Username="P2PClient", PasswordDigest="secret", Nonce="-1353447782", Created="2022-11-28T21:14:43+01:00"
Content-Type: 
Content-Length: 161

<body><CreateDate>1669666483</CreateDate><DevAuth>other secret</DevAuth><Nonce>864757875</Nonce><UserName>admin</UserName></body>

**Comment by user2684** [comment]
Where is this coming from? Is it an outgoing request from your camera?
Thanks for your availability to run some tests! Actually rather than sharing python code I think best would be if you are familiar with it of course to configure postman (https://open.imoulife.com/book/http/postman.html) so you can freely call any API, including those I've not implemented yet in our HA library. I'd give a try to https://open.imoulife.com/book/en/http/door/wakeUpDevice.html which *may* wake up the device

**Comment by checkiecheck** [comment]
Trying Postman and the package, just cant get the intial token API to work. Somehow it's not getting my appid and secret while they are set in the environment i'm using. I see other variables being set, just cant figure it at the moment.
{"result":{"msg":"appId为空。","code":"OP1008"},"id":"42"} meaning appid is empty.
dont get it and feel very stupid now :)

**Comment by checkiecheck** [comment]
additionally, the sample API modifyDeviceAlarmStatus DOES make the device go online with value =1.

So confirming the wakeup API is having no function at this device. any ideas whats next?

**Comment by user2684** [comment]
Ok, `wakeupcall `was actually just a guess since made for doorbell devices so makes sense it doesn't work. 
Interesting `modifyDeviceAlarmStatus `does instead wake up the device. Wonder if `setDeviceCameraStatus `is also waking up the device. If we cannot find a dedicated API to wake the device up, best we can do I guess is find an API call which is low-impact (e.g. getting the status of something rather than setting) and then use it to wake up the device before issuing any other command. Again, just guessing if we cannot find the proper call :-)

**Comment by checkiecheck** [comment]
YEs is does. Tried with:
`    "params":{
        "enableType":"closeCamera",
        "enable":true,`

for which i have really no clue what it means as the description in API docs is not that clear. 
Anyway, online =1 after calling the setDeviceCameraStatus.

**Comment by user2684** [comment]
Ok great so we now know we can wake up the camera :-) A few questions now:
- Any idea if closeCamera wakes up the camera when sending value true and put it to sleep back again with value false?
- Let's assume before acting on any switch we need to wake up the camera. Wonder how long it takes for the camera to pick up the following api call. If you call closeCamera and then another command, does it work or you need to wait a bit before calling another api call?
- I assume we do want to  wake up the camera for direct interaction with the switches but not for refreshing their values every 15 mins otherwise will run out of battery, makes sense? 
Thanks

**Comment by checkiecheck** [comment]
There is no api that results in device going back to sleep. Tried  closeCamera, but also closeDormant. Any moment the channel is on status 4 and an API is called, it wakes up. There is no case that forces it to 4. I dont think its really necesary, as soon as interaction goes silent, it auto sleeps in 10 seconds orso.
I saw in the Imou app, the close camera triggers the 'Camera shielding' toggle btw. Now i know what the api is for :). And hence the closeDormant is a better approach to wake up device.
The API response is slow, it waits until device is active. So you dont need to wait for execute next call, but wait for response. The response kind of fluctuates between 3 and 6 seconds, could even be longer i assume. So setting a time out of 10 seconds would make sense.
You last bullet has me thinking a few things. But lets start with the initial behaviour as it is now:
- the entities become very quickly unavailable currently. there is only active entities when devices is woken up and the poll is triggered.
- the camera stream is always NA (black in UI).
So options:
- stop polling for entities on battery devices, as it will make them unavailable 
- have a config setting for poll with wakeup, to be able to test battery life
- make call wake up when activating any toggle.
- think about periodic refreshing the still image. (api setDeviceSnap and use that for HA camera still)
- make different polling intervals , but didn't think that one through yet.

**Comment by user2684** [comment]
Ok understood thanks. So you are saying, let's send closeDormant true to wake up the camera. The API will not return until the camera is up so no need to add additional waiting time (maybe just a few seconds to be sure). And no need to put it to sleep again since it will go in sleep mode by itself after a few seconds. This may be the logic to go through *before* performing any action with the camera (manual or during a periodic refresh). 

Second topic is the availability of the camera. Right now is linked to the "online" status of the camera (e.g. "1" online, offline otherwise). This means I need to add a state ("4" dormant) and to make it available if in this state.

Now, about polling. It can be either taking place e.g. every 6 hours instead of 15 minutes or be disabled entirely.  I guess this should be configurable by the user.

Streaming, not sure if streaming is enabled the camera stays up but you cannot test I guess since always unavailable. If this is the case, other thing to understand is how to unbind from a live stream. I mean, there is an api for that but there is no concept of "stream closed" in HA as far as I know to terminate the stream on the other side.

Anything else I'm missing?

**Comment by checkiecheck** [comment]
First point: yes

second yes, with a note to 'device'oneline NOT the channel online

3rd, config would be most helptful

4th, not sure either. in the app, the stream dont stay open either. but not sure if its the app that stops or the device just says time out, going to sleep. 
So to me, an updated still image every 30 seoncds orso would do and possibly already drain battery a lot. So a config setting for that seperatly would be nice. 
The stream activation might be on webhook for motion detection, as the device should be awake already then, we might try to fetch live image too then.

**Comment by user2684** [comment]
First attempt with version 1.0.11, may not necessarily work since I'm working blind without a device with that capability to test :-) 
Have a loot at https://community.home-assistant.io/t/imou-life-cloud-integration/462439/128.
Some more implementation details:
- The device should be now available even when dormant so you can go and interact with it in a dormant state
- Any action is performed on any sensor or during a regular update, deviceOnline API is called so to refresh the current status, if domant, closeDormant is called and additional 4 seconds are added as waiting time. deviceOnline is called again to check the device is now online before proceeding. All of this is because I cannot keep track of the status of the device since goes to sleep by itself, I need to ensure before sending any command that is online and able to process the command.
- The above takes place **for each sensor** so there could be a lot of calls to the deviceOnline API but considering refresh should be pretty rare for these devices could be still acceptable
- Refresh time for all the sensors is 15 minutes, the default, regardless, so you may want to increase this to hours or a day to avoid consuming the batteries (and the API call limits)
-  Let's see if the logic works first and then we will investigate better the video streaming issue

**Comment by checkiecheck** [comment]
You sir, are even blind folded a million times better dev then I am in full visibility
![Screenshot_20221211-184803](https://user-images.githubusercontent.com/79155146/206920030-50030499-b403-45bc-bfaf-385619ccaa71.png)
Even got an camera image

**Comment by checkiecheck** [comment]
![Screenshot_20221211-184803~2](https://user-images.githubusercontent.com/79155146/206921370-9ed57b28-017f-4a08-8256-48475044274f.png)

**Comment by user2684** [comment]
Great! Glad to hear that. Keep me posted if you encounter any issue or strange behaviour along the way

**Comment by checkiecheck** [comment]
just spotted it is always reported online in HA. I think i know why, because the update polling wakes the device and there is never a dormant reponse somehow. Need to check if it does go to sleep from postman (later today) for battery usage. I lost about 5% battery overnight (but i have no reference nights to compare with).
I also could not find an API for battery level. Did you see that somewhere?

**Comment by checkiecheck** [comment]
Other question: should motion trigger a webhook or is only other alarms tied to webhooks?

**Comment by user2684** [comment]
The reason why shows up always online can be even simpler: If you e.g. refresh the data every 1 hour, it will always shows the last value, e.g. online. We can probably think of checking if it is online or not more frequently but the way it is designed the integration makes this very difficult to have different timers running. 

Regarding the battery, have you tried https://open.imoulife.com/book/en/http/door/getDevicePowerInfo.html? No idea if it would work with your camera but could be worth trying. 
How is it going in terms of battery usage generally speaking? Keep in mind that if you enable debug logging (https://github.com/user2684/imou_life#debugging) you should see all the details in terms of when the device is checked to be online, if a wake up call is made or not etc.

Motion (at least in my cameras) triggers an alarm which triggers a webhook.
Closing this as fixed but fell free to keep commenting :-)

**Comment by checkiecheck** [comment]
The dormant state is not really usefull, so lets not pursue this state showing in HA.

yes. devciepower info does return intersting info
{"result":{"msg":"Operation is successful.","code":"0","data":{"electricitys":[{"electric":"89","type":"battery"}]}},"id":"47"}

89 is in deed current battery level%


webhooks is still a mystery to me. Any suggestions where i should look for incoming traffic or find a test webhook option? (i do understand the working of webhooks, but really cant find any trace on imou currently)

**Comment by checkiecheck** [comment]
cool, battery drain visibility would be reaaly usefull..
with the webhooks enabled, it was drained in one night.  I had automation to share me a camera capture and button press. It continously triggered new webhooks, so every second the sensor poll update ran :)
Is there a way i can see the content of the webhooks? I think i want to distinguish few events, and the HA events dont give those (but only give 'state_change' event). Wonder if content of webhooks are more detailed so i can pick the specific events for motion only (or battery state)

**Comment by user2684** [comment]
Theoretically the webhook per-se should be server side. When you configure it, it will send the webhook, if not, the communication between the camera and Imou servers should take place anyway, only difference is that you will not receive it. This is because the Imou Life app is notified as well so cannot be dependent on your configuration.
Of course if you have configured the automation provided in the README, yes, then this will trigger a sensor refresh. You can view the content of the webhook by opening the automation, going to traces and reviewing the state changed section, you should see the json which is send over and customize the logic to avoid triggering the sensor refresh there. Let me know if makes sense. Thanks!

**Comment by checkiecheck** [comment]
Got it and now understand the drain better. Even without the sensor refresh, several webhooks come in.

`  json:
    deviceType: IPC
    msgType: online`
(twice)
then a
'  json:
    msgType: openCamera'

and later a
'    json:
    deviceType: IPC
    msgType: sleep
    desc:
      status: sleep'

So when the automation DOES do a sensor refresh. there is a new webhook and then it never ends.

Can i use the content of the webhook in an automation so i can make it better act on msgType?
then possibly an 'openCamera' could help me fetch a still image to display in HA

It would be awesome if we could make the 'sleep' message to update the entity state to be 'sleeping' as we cant do that by api easily.

**Comment by user2684** [comment]
Oh I see the issue. Sure you can, You can add template condition to your automation to proceed only on specific message types. You should have all the payload available in traces and you can add conditions based on trigger.json. If you need any help with this please let me know. This should be fixed not only for your camera even if of course with battery powered cameras it is way more impacting. I've opened up #45 to keep track of this different problem.
Good idea about to use the sleep message for updating the status otherwise the status will never be updated. Need to figure out the best way to do so since you cannot update the status of an entity from an automation (unless using some custom utilities) so maybe I need to add a service. Will think about it :-) 
Many Thanks

**Comment by user2684** [comment]
This should have been fixed now. You should see a "battery" sensor reporting the battery percentage. I've been working blind since I do not have such a camera to test so I hope it will work. I've also updated the automation template in the README file adding a condition to prevent triggering the refresh at every message type. Have a look at it, if it makes sense. Thanks.
Closing it for now, feel free to reopen again

**Comment by checkiecheck** [comment]
yessss.. got the battery sensor. Will look at automation template too later, didnt have the time yet.
thx for the BATT%, now i can trace battery life and do some charging planning !

**Comment by tango13** [comment]
> Trying Postman and the package, just cant get the intial token API to work. Somehow it's not getting my appid and secret while they are set in the environment i'm using. I see other variables being set, just cant figure it at the moment. {"result":{"msg":"appId为空。","code":"OP1008"},"id":"42"} meaning appid is empty. dont get it and feel very stupid now :)
> 
> never mind, the URl in the package was wrong. After changing it, it gives me a token. I'll shutup and try next steps

Sorry to revive this old discussion but I'm trying the same postman route for the cell go battery cam and I'm getting your same initial problems with postman.
You say the url in the package was wrong: can I ask you what you changed it into?
Thanks a lot.

**Comment by tango13** [comment]
Ok, I think I figured it out after carefully re-reading :), now I'm getting a token.
Will read the following posts and see whether they apply to my camera too.
Thanks.

**Comment by MiAutomations** [comment]
Hello 

I successfully integrate this camera model Cell Go in the HA using the IMOU LIfe Integration, but i still not able to view the live stream even if i activate the camera over the imou APP 

Right now I have the following sensors and entities available over this integration    

![image](https://github.com/user2684/imou_life/assets/47602733/e8b97b81-911d-4baa-9f2d-09e289794b60)
![image](https://github.com/user2684/imou_life/assets/47602733/d1af239a-140e-4c8f-9a86-6a1f48bb632b)

is there any way to get the live stream available ? 

Thank you

**Comment by tango13** [comment]
Have you checked you have imouapi library installed?
In my HA it wasn't automatically installed by the imou life integration, I had to install it manually via the pip command

`pip install imouapi`

**Comment by MiAutomations** [comment]
> Have you checked you have imouapi library installed? In my HA it wasn't automatically installed by the imou life integration, I had to install it manually via the pip command
> 
> `pip install imouapi`

Thank you for your reply.

I'm not able to run this command, I'm receiving a msg that PIP command is not available ...

Thank you
