### ISSUE TITLE
Motion Detection switch not working

### ISSUE THREAD

**Issue by marcodorini** [user2684/imou_life#60]
Hi, I'm a beginner with Home Assistant and I have this issue.
I have got 2 cameras: IPC-S42F-D and IPC-C26E-V2.
With the first one the switch "Motion Detection" works perfectly.
With the second one it doesn't work.
Can you please help me?

HA version: 2023.4.6
Supervisor: 2023.04.1
Operating system : 10.0
Frontend: 20230411.1

Thank you very much

Marco

[home-assistant_imou_life_2023-04-26T21-32-00.941Z.log](https://github.com/user2684/imou_life/files/11337477/home-assistant_imou_life_2023-04-26T21-32-00.941Z.log)

**Comment by marcodorini** [comment]
@user2684 can you please help me? I search everywhere but no results. 
Thank you very much

Best Regards

Marco

**Comment by afaucogney** [comment]
Hi, I'm in the same case
I do not have a Camera Motion Alarm for the C26E
It does work for the A22E

**Comment by user2684** [comment]
Hi guys, I see some errors in the logs related to downloading an image snapshot but nothing related to the "motion detection" switch. What happens when you toggle the switch? It restores back to the original position? What about the same switch in the Imou Life app? Does it stay off? Thanks

**Comment by marcodorini** [comment]
HI @user2684 
Thanks for the reply.
No, if I turn on or off Motion Detection from HA, in the imou app I have no effect.
If I turn on or off from the imou app, the switch in HA has no effect.
If you need more details or log let me know

Thanks again

Marco

**Comment by user2684** [comment]
Ok, the second scenario makes sense because the synchronization is not in real time, you need to click on the refresh data button to trigger an update of all the sensors. The first scenario instead is very strange because I don't see in the logs any error when you changed the status of the sensor. Wonder if with this camera they are using a different call.
Let's start from the second scenario which should tell us if anything is broken there. Try changing the status from the Imou app and click on the refresh data button in the device screen. If you can also enable debug logging for the integration (https://github.com/user2684/imou_life#debugging) before doing the test, could help. Thx

**Comment by marcodorini** [comment]
I do what you asked me but no way. Also if I refresh with the button the motion switch no change.
I attach you the debug. 
[Uploading home-assistant_imou_life_2023-05-07T15-07-13.788Z.log.txt…]()

**Comment by TheBisk** [comment]
Same camera and same problem. There is no binary_sensor for the motion alarm, only the switch that is not working.

**Comment by user2684** [comment]
Ok let me clarify: the switch is for enabling motion detection, the same that you have in your Imou Life app. The sensor instead register the motion and best way to make it working is through the callback url as detailed in the README. Just to clarify who does what :-) 
What I see in your logs @marcodorini are instead a couple of things, not sure if related with the issue or not: looks like we cannot get the preview of the image, this cause too many calls to the API which result in going over the allowed threshold with the Imou server and hence everything stops working since no more calls are actually accepted. So this is the first thing we need to address, waiting a bit more before downloading the preview image to avoid errors to occur which prevents the too many calls. Let me prioritize this in the roadmap

**Comment by user2684** [comment]
Added to https://github.com/user2684/imou_life/wiki/Known-Issues
