### ISSUE TITLE
Imou Cell Go camera supported 

### ISSUE THREAD

**Issue by MiAutomations** [user2684/imou_life#88]
Hello 

Once the camera modelo Imou Cell Go as improved in this release: 

![image](https://github.com/user2684/imou_life/assets/47602733/45341301-c0d2-465f-b08a-b0d981aefb2a)

But I'm still not able to view or access to the live stream, I'm question If I need to perform any further actions in order to get this?  
Once there are some people that have this feature working [https://github.com/user2684/imou_life/issues/55](url)

Thank you

**Comment by user2684** [comment]
Hi, the improvement of that version #55 was more on controlling the camera, not the video stream so it has no impact on it. 
Video stream issues are reported by different users across different models unfortunately, especially on shared devices. Not much I can do unfortunately since it is the remote API throwing an error and Imou is no more releasing updated documentation which can allow me to understand if they have changed something on their side :-(

**Comment by mcceeq** [comment]
Hi all, does anyone know how to access the HTTP stream for the Cell Go? I mean you can access it in the Imou app with the lan tool, so surely it's available. I just can't seem to find the right connection string.

**Comment by mcceeq** [comment]
@user2684 may I request additional sensors and controls to the Cell Go camera. How about a Charging sensor to show if the camera is plugged in and a control to change the Performance Mode.

**Comment by user2684** [comment]
Hi @mcceeq for the HTTP stream, I wonder if RTSP would work best, I've seen users using it but not myself so I do not have instructions to share. As for the Charging sensor, I couldn't find it among the sensors made available via the API unfortunately
